import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CartService } from '../../services/cart';
import { AuthService } from '../../services/auth';
import { OrderService } from '../../services/order';
import { ProductService } from '../../services/product';
import { CartItem } from '../../models/cart-item';
import { Order } from '../../models/order';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './checkout.html',
  styleUrls: ['./checkout.css'],
  encapsulation: ViewEncapsulation.None
})
export class CheckoutComponent implements OnInit {
  cartItems: CartItem[] = [];
  cartTotal: number = 0;
  tax: number = 0;
  finalTotal: number = 0;
  
  shippingInfo = {
    fullName: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    state: '',
    zipCode: ''
  };

  paymentInfo = {
    cardNumber: '',
    cardName: '',
    expiryDate: '',
    cvv: ''
  };

  isProcessing: boolean = false;
  orderComplete: boolean = false;
  orderNumber: string = '';

  constructor(
    private cartService: CartService,
    private authService: AuthService,
    private orderService: OrderService,
    private productService: ProductService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.cartService.cartItems$.subscribe(items => {
      this.cartItems = items;
      this.calculateTotals();
    });

    // Pre-fill user email
    const user = this.authService.getCurrentUser();
    if (user) {
      this.shippingInfo.email = user.email;
      this.shippingInfo.fullName = user.name;
    }

    // Redirect if cart is empty
    if (this.cartItems.length === 0) {
      this.router.navigate(['/customer-products']);
    }
  }

  calculateTotals(): void {
    this.cartTotal = this.cartService.getCartTotal();
    this.tax = this.cartTotal * 0.1;
    this.finalTotal = this.cartTotal + this.tax;
  }

  placeOrder(): void {
    if (!this.validateForms()) {
      alert('Please fill in all required fields');
      return;
    }

    this.isProcessing = true;

    // Simulate order processing
    setTimeout(() => {
      this.orderNumber = 'SS' + Math.floor(100000 + Math.random() * 900000);
      
      // Get current user
      const currentUser = this.authService.getCurrentUser();
      const userId = currentUser?.id || 0;
      
      // Create order object
      const order: Order = {
        id: 0, // Will be auto-generated by service
        userId: userId,
        items: this.cartItems,
        total: this.finalTotal,
        date: new Date().toISOString(),
        status: 'Completed',
        orderNumber: this.orderNumber,
        shippingInfo: this.shippingInfo,
        paymentInfo: {
          cardNumber: '****' + this.paymentInfo.cardNumber.slice(-4),
          cardName: this.paymentInfo.cardName
        }
      };
      
      // Prepare stock reduction data
      const stockUpdates = this.cartItems.map(item => ({
        productId: item.product.id,
        quantity: item.quantity
      }));
      
      console.log('📦 Processing order and reducing stock...');
      
      // Reduce stock first
      this.productService.reduceStockForOrder(stockUpdates).subscribe({
        next: (stockSuccess) => {
          if (stockSuccess) {
            console.log('✅ Stock reduced successfully');
            
            // Then save the order
            this.orderService.addOrder(order).subscribe({
              next: (orderSuccess) => {
                if (orderSuccess) {
                  console.log('✅ Order saved successfully:', order);
                  console.log('✅ Order Number:', this.orderNumber);
                  
                  this.orderComplete = true;
                  this.isProcessing = false;
                  
                  // Clear cart after successful order
                  this.cartService.clearCart();
                } else {
                  console.error('❌ Failed to save order');
                  this.isProcessing = false;
                  alert('Failed to place order. Please try again.');
                }
              },
              error: (error) => {
                console.error('❌ Error saving order:', error);
                this.isProcessing = false;
                alert('An error occurred while saving your order. Please contact support with order number: ' + this.orderNumber);
              }
            });
          } else {
            console.error('❌ Failed to reduce stock');
            this.isProcessing = false;
            alert('Some items may be out of stock. Please check your cart and try again.');
          }
        },
        error: (error) => {
          console.error('❌ Error reducing stock:', error);
          this.isProcessing = false;
          alert('An error occurred while processing your order. Please try again.');
        }
      });
    }, 2000);
  }

  validateForms(): boolean {
    // Basic validation
    const shippingValid = 
      this.shippingInfo.fullName &&
      this.shippingInfo.email &&
      this.shippingInfo.phone &&
      this.shippingInfo.address &&
      this.shippingInfo.city &&
      this.shippingInfo.state &&
      this.shippingInfo.zipCode;

    const paymentValid =
      this.paymentInfo.cardNumber &&
      this.paymentInfo.cardName &&
      this.paymentInfo.expiryDate &&
      this.paymentInfo.cvv;

    return !!(shippingValid && paymentValid);
  }

  continueShopping(): void {
    this.router.navigate(['/customer-products']);
  }

  onImageError(event: any): void {
    // Fallback image if the original fails to load
    event.target.src = 'https://via.placeholder.com/60x60/667eea/ffffff?text=Product';
  }
}
